db:
  production:
    adapter:  mysql2
    host:     localhost
    username: xxxxxxxx
    password: xxxxxxxx
    database: xxxxxxxx

  development:
    adapter:  mysql2
    host: 127.0.0.1
    username: root
    password: root
    database: test
